### ISSUE TITLE
selecting the software identifier

### ISSUE THREAD

**Issue by cboettig** [codemeta/codemetar#1]
@mbjones @gothub Just wanted to get your input on the choice of software identifier when generating codemeta.json from an R DESCRIPTION file.  According to our crosswalk, the identifier for an R package is the `Package` field of the DESCRIPTION; e.g. the package name (without a version).  Maybe we already went over this, but it seems like this isn't ideal -- e.g. assuming the package is archived on KNB or Zenodo, I'd expect this to be the DOI.  

In the `codemetar` implementation, I've allowed the function `write_codemeta()` to take an `id` as an argument.  (Currently it's generating a UUID, which is probably silly -- perhaps the default should be the package name, unless a DOI is provided?)  As always, there's a bit of a catch-22 in this process, in that we'd like to generate `codemeta.json` before uploading to Zenodo / KNB, but in the simplest workflow we only get the DOI after the upload is complete (Though I think you can reserve the DOI ahead of time with KNB; right? so in that case at least the package could handle this negotiation automatically I suppose).  Thoughts?

**Comment by mbjones** [comment]
Yeah, this needs discussion.  The crosswalk is indicating that the `Package` field in the R ecosystem is the unique identifier, but we know that it is neither globally unique, nor even unique within the R world if you consider package versioning.  So, I agree a different, globally unique id value should be used.  

Within the KNB, yes, you can pre-reserve a DOI so it can be incorporated into metadata before submission -- just for handling this case.  But it won't be a valid DOI until you actually create the object with it in the KNB.

**Comment by nuest** [comment]
With Zenodo, you can also pre-reserve a DOI, though I haven't found any documentation besides this [issue on the workflow](https://github.com/zenodo/zenodo/issues/742).

![pre-reserve doi zenodo](https://cloud.githubusercontent.com/assets/1698163/18277196/e48773ee-744d-11e6-8506-b8d2c450ad8a.png)

**Comment by cboettig** [comment]
@lnielsen @arfon Is it possible to reserve one's DOI before importing a tag from github to zenodo?  

Though with Zenodo's new versioned DOI's, after the initial import one could just use the DOI for the whole stack as the software `@id`, which would already always point to the latest version.  

That might go against the desire to have the metadata record / identifier / citation always be version-explicit, but it might also prove more practical in the long run(?)

**Comment by arfon** [comment]
> @lnielsen @arfon Is it possible to reserve one's DOI before importing a tag from github to zenodo?

I don't think it is sorry. @lnielsen will know for sure.

**Comment by cboettig** [comment]
Okay.  `codemetar` supports specifying the identifier at the top level, e.g.  in `write_codemeta()` / `create_codmeta()`, so for a user who does reserve the DOI in advance, this can be entered in this way.  Otherwise it just doesn't create an `@id` entry, which can presumably be filled out downstream.

**Comment by cboettig** [comment]
Closing since `codemetar` provides utilities to set/modify the identifier given in `codemeta.json` file, while details of where that identifier comes from and when will be determined by the user, repository, and external tools.
