### ISSUE TITLE
enable appveyor to check builds on windows (help needed)

### ISSUE THREAD

**Issue by cboettig** [codemeta/codemetar#18]
@mbjones @gothub For some reason, the codemeta repos don't show up for me in appveyor.  No idea why, I see appveyor is already enabled for the codemeta organization generally, (maybe I just have too many repos for appveyor to track).  Can you take a look and flip the switch to turn appveyor on?  Thanks!

**Comment by mbjones** [comment]
@cboettig I opened it on my account and it seemed to start the appveyor build for codemetar without any issues.  See: https://ci.appveyor.com/project/mbjones/codemetar

To start it, I had to grant read access to both the codemeta organization and then later to the codemetar repository.   Have you done both of those from your appveyor account?

**Comment by cboettig** [comment]
Thanks!

 I can now see all the repos in the codemeta org when I go to https://ci.appveyor.com/projects/new, before they weren't showing up.  You granted that access from the GitHub end or the Appveyor end?  From the GitHub end, I believe Appveyor was already on the org list of third-party access, https://github.com/organizations/codemeta/settings/oauth_application_policy , didn't see any way to add it under the repo's list of integrations, https://github.com/codemeta/codemeta/settings/installations (and I see it's still not listed there even though it's clearly enabled now), so I'm clearly doing something wrong with appveyor.  Haven't had trouble with other repos, they've always just showed up when I go to "new project" from Appveyor...

anyway, thanks for enabling!  will close this out.

**Comment by cboettig** [comment]
So I can now enable appveyor from my account too, https://ci.appveyor.com/project/cboettig/codemetar, though I'm really unclear on when appveyor uses the org namespace and when it uses the user namespace, e.g. I can only see the badge when I use `codemeta/codemetar`: https://ci.appveyor.com/api/projects/status/github/codemeta/codemetar?branch=master&svg=true

but can only see the actual appveyor results when I use a user namespace, `cboettig/codemetar`, https://ci.appveyor.com/project/cboettig/codemetar

while  https://ci.appveyor.com/project/codemeta/codemetar gives me a permission error.  In other org accounts I've always had everything just under the org namespace.  weird.
