### ISSUE TITLE
Typo in the A-codemeta-intro.Rmd file

### ISSUE THREAD

**Issue by adamhsparks** [codemeta/codemetar#37]
Line 113 reads:

> ... Almost any additional codemeta field (see `codemetar:::additional_codemeta_terms` for a list) and can be added to and read from the DESCRIPTION into a `codemeta.json` file.  

This sentence is not a proper sentence as far as I can tell. Perhaps you meant to remove the "and"?

**Comment by cboettig** [comment]
indeed thanks!
