### ISSUE TITLE
Consider parsing a CITATION file in the Package?

### ISSUE THREAD

**Issue by cboettig** [codemeta/codemetar#5]
Some R packages will provide additional citation information to a Software paper in a dedicated CITATION file, which R knows to parse when asked for `citation("packageName")`.  Ideally, `write_codemeta()` should check for such a file and automatically parse it for the `relatedPublication` field.

**Comment by mbjones** [comment]
Here are some examples that provide a citation file that we can use for testing:

- https://github.com/ropensci/datapack
- https://github.com/DataONEorg/rdataone
